name: CI

on:
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.9

jobs:
  dbt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dbt-duckdb
      run: |
        python -m pip install --upgrade pip
        python -m pip install dbt-duckdb

    - name: Run dbt
      run: dbt run
