name: CI

on:
  workflow_dispatch:

env:
  AWS_BUCKET_NAME: duck-pond
  AWS_REGION: eu-west-1

jobs:
  setup-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Upload to S3
      run: |
        aws s3api create-bucket \
          --bucket $BUCKET_NAME \
          --region $AWS_REGION
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
